pxc:
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: target.service=database
  environment:
    PXC_SST_PASSWORD: "**ChangeMe**"
    PXC_ROOT_PASSWORD: "**ChangeMe**"
    PXC_NODES: "**ChangeMe**"
    MY_IP: "**ChangeMe**"
  volumes:
  - /data/mysql:/var/lib/mysql
  image: nixel/rancher-percona-xtradb-cluster:v1.1.3
  tty: true
  privileged: true
  stdin_open: true
