pxc:
  restart: always
  environment:
    PXC_SST_PASSWORD: "**ChangeMe**"
    PXC_ROOT_PASSWORD: "**ChangeMe**"
    PXC_NODES: "**ChangeMe**"
    MY_IP: "**ChangeMe**"
  volumes:
  - /data/mysql:/var/lib/mysql
  - /var/log/mysql:/var/log/mysql
  image: nixel/rancher-percona-xtradb-cluster:latest
  privileged: true
